language: node_js
node_js:
  - 4
  - 6
  - 7

cache:
  directories:
    - $HOME/.pnpm-store

sudo: false
before_install:
  - npm install -g pnpm
install:
  - pnpm install
script:
  - npm test

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
